doctrine_migrations:
    migrations_paths:
        'DoctrineMigrations': '%kernel.project_dir%/migrations'
    custom_template: '%kernel.project_dir%/config/doctrine_migration.tpl'
    enable_profiler: false
