# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

parameters:
    app.path.chapter_images: '%kernel.project_dir%/public/chapters'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            string $chapterImagesPath: '%app.path.chapter_images%'

    App\:
        resource: '../src/'


